package cm.capstone.donsang.service;
import cm.capstone.donsang.dto.BusinessDtos.AlerteRequest; import cm.capstone.donsang.dto.ResponseDtos.CoordinateurDashboard; import cm.capstone.donsang.model.*; import cm.capstone.donsang.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*; import static cm.capstone.donsang.model.Enums.*;
@Service @RequiredArgsConstructor public class CoordinateurService {
 private final UtilisateurRepository users; private final ProfilEtablissementRepository etablissements; private final ProfilDonneurRepository donneurs; private final DemandeUrgenteRepository demandes; private final DonRepository dons; private final NotificationRepository notifications; private final EmailService email;
 @Transactional public void valider(Long id,boolean ok){var e=etablissements.findById(id).orElseThrow();e.setStatutValidation(ok?StatutValidation.VALIDE:StatutValidation.REJETE);etablissements.save(e);notifications.save(Notification.builder().utilisateur(e.getUtilisateur()).message(ok?"Votre établissement a été validé.":"Votre établissement a été rejeté.").type(TypeNotification.INFO).lue(false).dateEnvoi(LocalDateTime.now()).build());}
 @Transactional public void desactiver(Long id){var u=users.findById(id).orElseThrow();u.setCompteActif(false);users.save(u);}
 public CoordinateurDashboard dashboard(){Map<String,Long> m=new LinkedHashMap<>();for(String g:List.of("A+","A-","B+","B-","AB+","AB-","O+","O-"))m.put(g,donneurs.countByGroupeSanguin(g));return new CoordinateurDashboard(donneurs.count(),etablissements.countByStatutValidation(StatutValidation.VALIDE),dons.countByStatutValidation(StatutDon.VALIDE),demandes.countByStatut(StatutDemande.OUVERTE),m);}
 @Transactional public void alerte(AlerteRequest r){donneurs.findAll().stream().filter(d->r.groupeSanguin().equalsIgnoreCase(d.getGroupeSanguin())).forEach(d->{notifications.save(Notification.builder().utilisateur(d.getUtilisateur()).message(r.message()).type(TypeNotification.ALERTE_GENERALE).lue(false).dateEnvoi(LocalDateTime.now()).build());email.send(d.getUtilisateur().getEmail(),"Alerte don de sang",r.message(),TypeEmail.ALERTE);});}
}
