package cm.capstone.donsang.service;
import cm.capstone.donsang.dto.BusinessDtos.*; import cm.capstone.donsang.dto.ResponseDtos.*; import cm.capstone.donsang.model.*; import cm.capstone.donsang.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*; import static cm.capstone.donsang.model.Enums.*;
@Service @RequiredArgsConstructor public class DonService {
 private final UtilisateurRepository users; private final ProfilDonneurRepository donneurs; private final ProfilEtablissementRepository etablissements; private final RendezVousDonRepository rdvs; private final DemandeUrgenteRepository demandes; private final DonRepository dons; private final StockSangRepository stocks;
 public ProfilDonneur donneur(String email){return donneurs.findByUtilisateurId(users.findByEmail(email).orElseThrow().getId()).orElseThrow();}
 public ProfilEtablissement etablissement(String email){return etablissements.findByUtilisateurId(users.findByEmail(email).orElseThrow().getId()).orElseThrow();}
 public List<ProfilEtablissement> etablissementsValides(){return etablissements.findAll().stream().filter(e->e.getStatutValidation()==StatutValidation.VALIDE).toList();}
 public List<DemandeUrgente> demandes(String email){return demandes.findByStatutAndGroupeSanguinRecherche(StatutDemande.OUVERTE,donneur(email).getGroupeSanguin());}
 @Transactional public RendezVousDon prendreRdv(String email,RendezVousRequest r){var d=donneur(email);var e=etablissements.findById(r.etablissementId()).orElseThrow();if(e.getStatutValidation()!=StatutValidation.VALIDE)throw new IllegalArgumentException("Établissement non validé");var q=r.demandeId()==null?null:demandes.findById(r.demandeId()).orElseThrow();if(r.dateRendezVous().isBefore(LocalDate.now()))throw new IllegalArgumentException("Date invalide");return rdvs.save(RendezVousDon.builder().donneur(d).etablissement(e).demande(q).dateRendezVous(r.dateRendezVous()).creneauHoraire(r.creneauHoraire()).statut(StatutRendezVous.PLANIFIE).build());}
 @Transactional public void annuler(String email,Long id){var r=rdvs.findById(id).orElseThrow();if(!r.getDonneur().getId().equals(donneur(email).getId()))throw new IllegalArgumentException("Accès refusé");if(r.getDateRendezVous().isBefore(LocalDate.now()))throw new IllegalArgumentException("Rendez-vous déjà passé");r.setStatut(StatutRendezVous.ANNULE);rdvs.save(r);}
 public List<Don> historique(String email){return dons.findByDonneurIdOrderByDateDonDesc(donneur(email).getId());}
 @Transactional public DemandeUrgente creerDemande(String email,DemandeRequest r){var e=etablissement(email);if(e.getStatutValidation()!=StatutValidation.VALIDE)throw new IllegalArgumentException("Établissement non validé");return demandes.save(DemandeUrgente.builder().etablissement(e).groupeSanguinRecherche(r.groupeSanguinRecherche()).quantiteNecessaire(r.quantiteNecessaire()).niveauUrgence(NiveauUrgence.valueOf(r.niveauUrgence().toUpperCase())).description(r.description()).dateCreation(LocalDateTime.now()).dateLimite(r.dateLimite()).statut(StatutDemande.OUVERTE).build());}
 @Transactional public void cloturer(String email,Long id){var d=demandes.findById(id).orElseThrow();if(!d.getEtablissement().getId().equals(etablissement(email).getId()))throw new IllegalArgumentException("Accès refusé");d.setStatut(StatutDemande.CLOTUREE);demandes.save(d);}
 public List<StockSang> stock(String email){return stocks.findByEtablissementId(etablissement(email).getId());}
 @Transactional public StockSang updateStock(String email,String groupe,StockRequest r){var e=etablissement(email);var s=stocks.findByEtablissementIdAndGroupeSanguin(e.getId(),groupe).orElse(StockSang.builder().etablissement(e).groupeSanguin(groupe).build());s.setQuantitePoches(r.quantitePoches());s.setDateMiseAJour(LocalDateTime.now());return stocks.save(s);}
 public List<RendezVousDon> rdvsEtablissement(String email){return rdvs.findByEtablissementId(etablissement(email).getId());}
 @Transactional public void confirmerRdv(String email,Long id){var r=rdvs.findById(id).orElseThrow();if(!r.getEtablissement().getId().equals(etablissement(email).getId()))throw new IllegalArgumentException("Accès refusé");r.setStatut(StatutRendezVous.CONFIRME);rdvs.save(r);}
 @Transactional public Don enregistrerDon(String email,DonRequest req){var e=etablissement(email);var r=rdvs.findById(req.rendezVousId()).orElseThrow();if(!r.getEtablissement().getId().equals(e.getId()))throw new IllegalArgumentException("Rendez-vous étranger");if(r.getStatut()!=StatutRendezVous.CONFIRME&&r.getStatut()!=StatutRendezVous.PLANIFIE)throw new IllegalArgumentException("Rendez-vous non valide");r.setStatut(StatutRendezVous.EFFECTUE);rdvs.save(r);var d=dons.save(Don.builder().rendezVous(r).donneur(r.getDonneur()).etablissement(e).dateDon(LocalDate.now()).quantiteMl(req.quantiteMl()).groupeSanguin(req.groupeSanguin()).statutValidation(StatutDon.VALIDE).build());r.getDonneur().setDateDernierDon(LocalDate.now());donneurs.save(r.getDonneur());var s=stocks.findByEtablissementIdAndGroupeSanguin(e.getId(),req.groupeSanguin()).orElse(StockSang.builder().etablissement(e).groupeSanguin(req.groupeSanguin()).quantitePoches(0).build());s.setQuantitePoches(s.getQuantitePoches()+1);s.setDateMiseAJour(LocalDateTime.now());stocks.save(s);return d;}
 public DonneurDashboard dashboardDonneur(String email){var d=donneur(email);long total=dons.countByDonneurIdAndStatutValidation(d.getId(),StatutDon.VALIDE);LocalDate prochain=d.getDateDernierDon()==null?LocalDate.now():d.getDateDernierDon().plusDays(90);boolean ok=!prochain.isAfter(LocalDate.now());return new DonneurDashboard(total,ok?"Aujourd'hui":prochain.toString(),ok?"ÉLIGIBLE MAINTENANT":"NON ÉLIGIBLE",total*3,demandes(email).size());}
 public EtablissementDashboard dashboardEtablissement(String email){var e=etablissement(email);var now=LocalDate.now();return new EtablissementDashboard(stock(email).stream().map(s->new StockDto(s.getId(),s.getGroupeSanguin(),s.getQuantitePoches(),s.getDateMiseAJour())).toList(),demandes.findByEtablissementId(e.getId()).stream().filter(x->x.getStatut()==StatutDemande.OUVERTE).count(),rdvs.countByEtablissementIdAndDateRendezVousBetween(e.getId(),now.with(java.time.DayOfWeek.MONDAY),now.with(java.time.DayOfWeek.MONDAY).plusDays(6)),dons.countByEtablissementIdAndDateDonBetween(e.getId(),now.withDayOfMonth(1),now.withDayOfMonth(now.lengthOfMonth())));}
}
